version: '3.8'

networks:
  default:
    name: the_printer_service
    external: true

services:
  app:
    build: ./
    environment:
      - "LISTEN_PORT=3000"
      - "NPM_CONFIG_LOGLEVEL=verbose"
      - "REQUEST_BODY_LIMIT=50mb"
    restart: unless-stopped
    ports:
    - '3000:3000'
    security_opt:
      - seccomp=./chrome.json
    networks:
      - default

